# CodeSandbox supports debian & ubuntu based images
FROM debian

# Example; install htop by default
RUN apt update -y && apt install -y openjdk-17-jdk && apt install -y openjdk-17-jre && apt install -y wget && apt install -y curl
